name: CI

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

jobs:
  test:
    name: Run Anchor Tests
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup Rust Toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: "1.89.0"
          components: rustfmt, clippy

      - name: Run Anchor Tests
        uses: metadaoproject/anchor-test@v2.3
        with:
          anchor-version: "0.32.1"
          solana-cli-version: "2.1.7"
          node-version: "20"
